document.writeln("<!--导航-开始-->");
document.writeln("<nav class=\'navbar navbar-default\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("                <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("        </div>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li class=\'active\'><a href=\'#\'>首页<span class=\'sr-only\'></span></a></li>");
document.writeln("                <li><a href=\'alliance.html\'>联盟简介</a></li>");
document.writeln("                <li><a href=\'luatest\index.html'>响应时间为5秒</a></li>");
document.writeln("                <li><a href=\'dir\'>目录遍历漏洞</a></li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>敏感信息<span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'ifl/andir.html\'>敏感信息１</a></li>");
document.writeln("                        <li><a href=\'ifl/iisdir.html\'>IIS敏感信息２</a></li>");
document.writeln("                        <li><a href=\'ifl/netelk.html\'>敏感信息３</a></li>");
document.writeln("                        <li><a href=\'ifl/netslk.html\'>敏感信息4</a></li>");
document.writeln("                        <li><a href=\'ifl/pelde.html\'>敏感信息5</a></li>");
document.writeln("                        <li><a href=\'ifl/pelnot.html\'>敏感信息6</a></li>");
document.writeln("                        <li><a href=\'ifl/peloe.html\'>敏感信息7</a></li>");
document.writeln("                        <li><a href=\'ifl/pelpe.html\'>敏感信息8</a></li>");
document.writeln("                        <li><a href=\'ifl/pelwarn.html\'>敏感信息9</a></li>");
document.writeln("                        <li><a href=\'ifl/pinh.html\'>敏感信息10</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>下载<span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'docs/5.7z\'>.7z文件</a></li>");
document.writeln("                        <li><a href=\'docs/Hash_1.0.4_XiaZaiBa.exe\'>.exe文件</a></li>");
document.writeln("                        <li><a href=\'docs/1000.mp3\'>.mp3文件</a></li>");
document.writeln("                        <li><a href=\'docs/random.php\'>.php文件</a></li>");
document.writeln("                        <li><a href=\'docs/5.rar\'>.rar文件</a></li>");
document.writeln("                        <li><a href=\'docs/hello.txt\'>.txt文件</a></li>");
document.writeln("                        <li><a href=\'docs/hello.doc\'>.doc文件</a></li>");
document.writeln("                        <li><a href=\'docs/hellp.html\'>.html文件</a></li>");
document.writeln("                        <li><a href=\'docs/hellp.asp\'>.asp文件</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>货运信息<span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'freight-info.html\'>货运信息发布</a></li>");
document.writeln("                        <li><a href=\'freight-details.html\'>货运信息详情</a></li>");
document.writeln("                        <li><a href=\'freight-map.html\'>货运地图</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>司机读本<span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'driving-knowledge.html\'>驾驶常识</a></li>");
document.writeln("                        <li><a href=\'driving-knowledge.html\'>政策法规</a></li>");
document.writeln("                        <li><a href=\'driving-knowledge.html\'>卡车评估</a></li>");
document.writeln("                        <li><a href=\'driving-knowledge.html\'>修车指导</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>行内互动<span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'line-interaction.html\'>驾驶员记分</a></li>");
document.writeln("                        <li><a href=\'line-interaction.html\'>卡车求购转让</a></li>");
document.writeln("                        <li><a href=\'line-interaction.html\'>招聘信息</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'contact-us.html\'>联系我们</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</nav>");
